/** @file Contains raw mp3 data. Automatically generated by converter.py */
#ifndef MP3_DATA_H_
#define MP3_DATA_H_
#include "config.h"
#ifdef MP3_DATA_FUR_ELISE
extern const char mp3_data[599832];
#endif
#ifdef MP3_DATA_ZHONTI
extern const char mp3_data[776592];
#endif
#ifdef MP3_DATA_FLY
extern const char mp3_data[480672];
#endif
#ifdef MP3_DATA_ELECTRICITY
extern const char mp3_data[768780];
#endif
#ifdef MP3_DATA_THUNDER
extern const char mp3_data[665316];
#endif
#ifdef MP3_DATA_CRAZY
extern const char mp3_data[810540];
#endif
#ifdef MP3_DATA_NONE
extern const char mp3_data[1368];
#endif
#ifdef MP3_DATA_MUSIC
extern const char mp3_data[564228];
#endif
#endif /* MP3_DATA_music_H_ */
